# Generated by Django 4.2.1 on 2023-05-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(default='', max_length=25)),
                ('register', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=25)),
                ('short_name', models.CharField(default='', max_length=25)),
                ('type', models.CharField(default='', max_length=25)),
                ('phone', models.CharField(default='', max_length=25)),
                ('mail', models.CharField(default='', max_length=25)),
                ('men_cnt', models.IntegerField(default=0, max_length=11)),
                ('license_date', models.IntegerField(default=0, max_length=11)),
                ('license_attent_date', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='confirm_mail_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('mail', models.CharField(default='', max_length=25)),
                ('msg', models.CharField(default='', max_length=25)),
                ('is_active', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='human_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(default='', max_length=25)),
                ('com_id', models.IntegerField(default=0, max_length=11)),
                ('dep_id', models.IntegerField(default=0, max_length=11)),
                ('app_id', models.IntegerField(default=0, max_length=11)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('first_name', models.CharField(default='', max_length=25)),
                ('gender', models.IntegerField(default=0, max_length=11)),
                ('phone', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(default='', max_length=25)),
                ('work_type_id', models.IntegerField(default=0, max_length=11)),
                ('is_moderator', models.IntegerField(default=0, max_length=11)),
                ('code', models.CharField(default='', max_length=25)),
                ('is_attendace', models.IntegerField(default=0, max_length=11)),
                ('time_access_id', models.IntegerField(default=0, max_length=11)),
                ('salary_id', models.IntegerField(default=0, max_length=11)),
                ('author_id', models.IntegerField(default=0, max_length=11)),
                ('create_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='login_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('phone', models.CharField(default='', max_length=25)),
                ('mail', models.CharField(default='', max_length=25)),
                ('enc_password', models.CharField(default='', max_length=250)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='tree_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, max_length=11)),
                ('root_id', models.IntegerField(default=0, max_length=11)),
                ('type', models.IntegerField(default=0, max_length=11)),
                ('name', models.CharField(default='', max_length=25)),
                ('short_name', models.CharField(default='', max_length=25)),
                ('salary', models.IntegerField(default=0, max_length=11)),
                ('salary_type', models.CharField(default='', max_length=25)),
                ('men_cnt', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
    ]
