# Generated by Django 4.2.1 on 2023-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(default='', max_length=25)),
                ('register', models.CharField(default='', max_length=25)),
                ('name', models.CharField(default='', max_length=25)),
                ('short_name', models.CharField(default='', max_length=25)),
                ('type', models.CharField(default='', max_length=25)),
                ('phone', models.CharField(default='', max_length=25)),
                ('mail', models.CharField(default='', max_length=25)),
                ('men_cnt', models.IntegerField(default=0, max_length=11)),
                ('license_date', models.IntegerField(default=0, max_length=11)),
                ('license_attent_date', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='confirm_mail_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('mail', models.CharField(default='', max_length=25)),
                ('msg', models.CharField(default='', max_length=25)),
                ('is_active', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='direct_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('description', models.CharField(default='', max_length=25)),
                ('is_active', models.IntegerField(default=0, max_length=11)),
                ('com_id', models.IntegerField(default=0, max_length=11)),
                ('author_id', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
                ('_cron_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='direct_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.IntegerField(default=0, max_length=11)),
                ('direct_group_id', models.IntegerField(default=0, max_length=11)),
                ('days', models.IntegerField(default=0, max_length=2)),
                ('is_holiday', models.IntegerField(default=0, max_length=11)),
                ('is_flexible', models.IntegerField(default=0, max_length=11)),
                ('start_date', models.IntegerField(default=0, max_length=11)),
                ('between_start_date', models.IntegerField(default=0, max_length=11)),
                ('end_date', models.IntegerField(default=0, max_length=11)),
                ('between_end_date', models.IntegerField(default=0, max_length=11)),
                ('is_lunch', models.IntegerField(default=0, max_length=11)),
                ('lunch_start_date', models.IntegerField(default=0, max_length=11)),
                ('lunch_end_date', models.IntegerField(default=0, max_length=11)),
                ('missed_work_money', models.IntegerField(default=0, max_length=11)),
                ('create_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='direct_schedule_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('direct_group_id', models.IntegerField(default=0, max_length=11)),
                ('is_type', models.IntegerField(default=0, max_length=11)),
                ('is_lunch', models.IntegerField(default=0, max_length=11)),
                ('time_1', models.IntegerField(default=0, max_length=11)),
                ('time_2', models.IntegerField(default=0, max_length=11)),
                ('time_3', models.IntegerField(default=0, max_length=11)),
                ('time_4', models.IntegerField(default=0, max_length=11)),
                ('description', models.CharField(default='', max_length=25)),
                ('create_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='direct_user_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_group_id', models.IntegerField(default=0, max_length=11)),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('create_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='human_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.CharField(default='', max_length=25)),
                ('com_id', models.IntegerField(default=0, max_length=11)),
                ('dep_id', models.IntegerField(default=0, max_length=11)),
                ('app_id', models.IntegerField(default=0, max_length=11)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('first_name', models.CharField(default='', max_length=25)),
                ('gender', models.IntegerField(default=0, max_length=11)),
                ('phone', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(default='', max_length=25)),
                ('work_type_id', models.IntegerField(default=0, max_length=11)),
                ('is_moderator', models.IntegerField(default=0, max_length=11)),
                ('code', models.CharField(default='', max_length=25)),
                ('is_attendace', models.IntegerField(default=0, max_length=11)),
                ('time_access_id', models.IntegerField(default=0, max_length=11)),
                ('salary_id', models.IntegerField(default=0, max_length=11)),
                ('author_id', models.IntegerField(default=0, max_length=11)),
                ('create_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ip_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=25)),
                ('author_id', models.IntegerField(default=0, max_length=11)),
                ('desc', models.CharField(default='', max_length=25)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='login_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('phone', models.CharField(default='', max_length=25)),
                ('mail', models.CharField(default='', max_length=25)),
                ('enc_password', models.CharField(default='', max_length=250)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='request_access_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('author_id', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='request_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0, max_length=11)),
                ('type_id', models.IntegerField(default=0, max_length=11)),
                ('com_id', models.IntegerField(default=0, max_length=11)),
                ('dep_id', models.IntegerField(default=0, max_length=11)),
                ('app_id', models.IntegerField(default=0, max_length=11)),
                ('shift_user_id', models.IntegerField(default=0, max_length=11)),
                ('shift_user_name', models.CharField(default='', max_length=25)),
                ('shift_date', models.IntegerField(default=0, max_length=11)),
                ('confirm_date', models.IntegerField(default=0, max_length=11)),
                ('s_date', models.IntegerField(default=0, max_length=11)),
                ('e_date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='tree_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, max_length=11)),
                ('root_id', models.IntegerField(default=0, max_length=11)),
                ('type', models.IntegerField(default=0, max_length=11)),
                ('name', models.CharField(default='', max_length=25)),
                ('short_name', models.CharField(default='', max_length=25)),
                ('salary', models.IntegerField(default=0, max_length=11)),
                ('salary_type', models.CharField(default='', max_length=25)),
                ('men_cnt', models.IntegerField(default=0, max_length=11)),
                ('date', models.IntegerField(default=0, max_length=11)),
            ],
        ),
    ]
